Vagrant.configure("2") do |config|
  config.vm.box = "janihur/ubuntu-1604-lxde-desktop"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "Attacker"
    config.vm.network "private_network", ip: "10.0.0.10", :name => 'vboxnet0', :adapter => 2
  end

  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
    chef.add_recipe "metasploit"
    chef.add_recipe "java"
    chef.json = {
      "java" => {
        install_flavor: 'openjdk',
        jdk_version: '8'
      }
    }
  end

  # French keyboard
  # TODO

  # Synced folders
  config.vm.synced_folder "./files", "/home/vagrant/scripts"

  # Install ZAP
  config.vm.provision "shell", path: "script/zap-install.sh"
end
