Vagrant.configure("2") do |config|
  config.vm.box = "janihur/ubuntu-1604-lxde-desktop"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "Attacker"
    config.vm.network "private_network", ip: "10.0.0.10", :name => 'vboxnet0', :adapter => 2
  end

  # French keyboard
  # config.vm.provision "shell", inline: "setxkbmap fr"

  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
    chef.add_recipe "metasploit"
  end
end
