Vagrant.configure("2") do |config|
  config.vm.box = "scotch/box"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "Vulnerable web server"
    config.vm.network "private_network", ip: "10.0.0.20", :name => 'vboxnet0', :adapter => 2
  end

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
  end

  # Synced folders
  config.vm.synced_folder "./app", "/var/www/public", :owner => "www-data", :group => "www-data"
end
